USE `RDCRMS`;

CREATE TABLE `CERTIFICATE_REQUESTS` (
      `APPLICATION_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
      `FULL_NAME` VARCHAR(40),
      `AADHAAR_CARD_NUMBER` BIGINT,
      `GENDER` VARCHAR(10),
      `DATE_OF_BIRTH` DATE,
      `FATHER_NAME` VARCHAR(40),
      `MOTHER_NAME` VARCHAR(40),
      `VILLAGE` VARCHAR(30),
      `MANDAL` VARCHAR(20),
      `DISTRICT` VARCHAR(30),
      `STATE` VARCHAR(15),
      `COUNTRY` VARCHAR(15),
      `EMAIL` VARCHAR(30),
      `MOBILE_NUMBER` BIGINT,
      `RATION_CARD_NUMBER` BIGINT,
      `TYPE_OF_DOCUMENT` VARCHAR(30),
      `PURPOSE_OF_CERTIFICATE` VARCHAR(20),
       `SUBMITTED_DATE` TINYINT,
      `SUBMITTED_MONTH` VARCHAR(10),
      `SUBMITTED_YEAR` INT,
       `DESIGNATION` VARCHAR(20),
       `YEARLY_INCOME` DECIMAL,
      `TYPE_OF_HOUSE` VARCHAR(20),
      `PHYSICALLY_HANDICAPPED` VARCHAR(5),
      `GOVERNMENT_EMPLOYEE` VARCHAR(5),
      `CASTE` VARCHAR(5),
      `SUB_CASTE` VARCHAR(20),
      `DATE_OF_DEATH` DATE,
      `STATUS` VARCHAR(10),
      `COMMENTS` VARCHAR(50),
      `CREATED_AT` DATE,
      `UPDATED_AT` DATE
);

INSERT INTO `CERTIFICATE_REQUESTS` (
      `FULL_NAME`,
      `AADHAAR_CARD_NUMBER`,
      `GENDER`,
      `DATE_OF_BIRTH`,
      `FATHER_NAME`,
      `MOTHER_NAME`,
      `VILLAGE`,
      `MANDAL`,
      `DISTRICT`,
      `STATE`,
      `COUNTRY`,
      `EMAIL`,
      `MOBILE_NUMBER`,
      `RATION_CARD_NUMBER`,
      `TYPE_OF_DOCUMENT`,
      `PURPOSE_OF_CERTIFICATE`,
      `SUBMITTED_DATE`,
      `SUBMITTED_MONTH`,
      `SUBMITTED_YEAR`,
      `DESIGNATION`,
      `YEARLY_INCOME`,
      `TYPE_OF_HOUSE`,
      `PHYSICALLY_HANDICAPPED`,
      `GOVERNMENT_EMPLOYEE`,
      `CASTE`,
      `SUB_CASTE`,
      `DATE_OF_DEATH`,
      `STATUS`,
      `COMMENTS`,
      `CREATED_AT`,
      `UPDATED_AT`
) VALUES (
      'Bhavana',
      123456789012,
      'Female',
      '2003-05-15',
      'Kamalakar',
      'Jyothi',
      'GVR Palem',
      'Venkatachalam',
      'Nellore',
      'Andhra Pradesh',
      'India',
      'bhavana@gmail.com',
      9876543210,
      112233445566,
      'Caste',
      'Education',
      09,
      'November',
      2024,
      'Student',
      35000.00,
      'Owned',
      'No',
      'No',
      'OBC',
      'Yadav',
      NULL,
      'Pending',
      'Awaiting verification',
      '2024-11-09',
      '2024-11-09'
);


